### ISSUE TITLE
Use of the Ignored Tags or tag handling

### ISSUE THREAD

**Issue by Izaya00** [DeepLcom/google-sheets-example#11]
Thanks for the script. J'ai du texte à traduire mais avec des balises HTML tel que '\n, [/cg_accordion], < li><, /li> < ul> < /p> < p>. So the text translates badly and produces errors. So I have to use igored tag or tag_handling. However, I am not comfortable with the code to add it myself so if anyone has the solution for me to integrate this into the script, it would help me a lot.

**Comment by daniel-jones-deepl** [comment]
Hi @Izaya00, I've just merged an update to this script that allows additional options, you can read about the feature [here](https://github.com/DeepLcom/google-sheets-example#additional-options). This will allow you specify the `tag_handling` and `ignore_tags` options however you need for your data.

**Comment by Izaya00** [comment]
I can't thank you enough, you save me a lot of time, thank you
