### ISSUE TITLE
Support for arrayformula?

### ISSUE THREAD

**Issue by orschiro** [DeepLcom/google-sheets-example#14]
Hi guys, 

This is wonderful, thank you so much!

One request:

Would it be possible to support the ARRAYFORMULA?

Instead of having to type in the DEEPLTRANSLATE formula into each cell one by one, with the arrayformula you could write something like this across cell ranges:

    =ARRAYFORMULA(DEEPLTRANSLATE,A:A,"en","de")

This would translate all cells in column A. 

What do you think?

Thank you!

**Comment by seekuehe** [comment]
Hi there, as stated in the README, this sample project is not actively supported by our team and serves more as an inspiration and starting point for users. 

We welcome contributions, so if you want to open a pull request with your improvements, we will surely review (and likely merge) it.
