### ISSUE TITLE
Loading continues

### ISSUE THREAD

**Issue by sasamasama** [DeepLcom/google-sheets-example#5]
Hi, 
When I try to translate from EN to another language, the cell shows "Loading" and the translation continues without any error message.   Could you please tell me what would be an issue?

**Comment by daniel-jones-deepl** [comment]
Hi @sasamasama, this could be an error in the the retranslation-detection. Unfortunately it is still a little unreliable. The code line in question is [line 57](https://github.com/DeepLcom/google-sheets-example/blob/main/DeepL.gs#L57). The line looks like this:
```
    if (cell.getDisplayValue() !== "" && cell.getDisplayValue() !== "Loading...") {
```
You could try changing this line in your script to fix the problem.

First, try modify the loading text to match exactly what you see, for example:
```
    if (cell.getDisplayValue() !== "" && cell.getDisplayValue() !== "Loading") {
```
or secondly, you could disable this feature entirely, for example:
```
    if (false) {
```
Please let me know if that works for you.

**Comment by sasamasama** [comment]
Hi  @daniel-jones-deepl 

Thank you very much for your prompt advice.
Modification didn't work but the disablement worked!

Thank you again!

**Comment by daniel-jones-deepl** [comment]
Ok, great that disabling it worked. I'd advise you to look into the [Copy-paste Values only](https://github.com/DeepLcom/google-sheets-example#copy-paste-values-only) section in the readme though, to avoid translating more characters than you plan.

**Comment by sasamasama** [comment]
Thank you and I will refer to the link provided and set the limit to avoid going over 500,000 characters.

**Comment by mike-winters-deepl** [comment]
@daniel-jones-deepl OK to close this issue after this week's update?
