### ISSUE TITLE
Re-translations - developer metadata

### ISSUE THREAD

**Issue by machj** [DeepLcom/google-sheets-example#7]
To solve a re-translation issue, you can store translated pairs as developer metadata. In the DeepLTranslate() function, you should check if the "sourceLang|targetLang|input" key already exists, if so, there is no need to translate and the metadata value for the key can be used. If the key doesn't exist, the translation should be performed and the result stored as the metadata with the appropriate key. Similarly for glossaries. There could be a macro to delete all developer metadata to enable re-translation.

Small example to store and read metadata:

```
  var sheet = SpreadsheetApp.getActive();
  var row = sheet.getRange("1:1");
  row.addDeveloperMetadata("en-GB|de|Hello world!", "Hallo Welt!");
  var test=row.getDeveloperMetadata()[0];
  console.log(test.getKey());
  console.log(test.getValue());
```

**Comment by daniel-jones-deepl** [comment]
Hi @machj, thank you for the suggestion! This is a great idea. I looked into the [developer metadata documentation](https://developers.google.com/sheets/api/guides/metadata#metadata_storage_limits) and unfortunately there is a limit of 30K characters per sheet.

We could minimize the cache size by hashing the input text, but I think it will be common to hit that limit. It's probably still worth looking into though.
