### ISSUE TITLE
Error: Length

### ISSUE THREAD

**Issue by Mixlawreventon** [DeepLcom/google-sheets-example#8]
Hi, Could you help with this one? I'm getting these error:

```
TypeError: Cannot read properties of undefined (reading 'length')
DeepLTranslate	@ DeepL.gs:78
```
![error-deep-l](https://user-images.githubusercontent.com/121884496/210393192-1ad56384-8420-4d17-bf51-f96e7e0e7f20.png)

**Comment by daniel-jones-deepl** [comment]
I've just merged an additional check for a missing input text.
